services:
  bookmarker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookmarker.rule=Host(`bookmarker.alau.at`)"
      - "traefik.http.routers.bookmarker.entrypoints=web"
      - "traefik.http.routers.bookmarker.service=bookmarker"
      - "traefik.http.services.bookmarker.loadbalancer.server.port=4002"
    networks:
      - frontend

networks:
  frontend:
    external: true